name: CD Build
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_qhrArtifactoryUsername: "${{ vars.ARTIFACTORY_IDENTITY_TOKEN_USER }}"
  ORG_GRADLE_PROJECT_qhrArtifactoryPassword: "${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}"

  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "zulu"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ssh-key: "${{ secrets.SSH_KEY_GITHUB }}"

      - name: 'Inform Gradle of CI Tag Build'
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "ORG_GRADLE_PROJECT_ciTag=true" >> $GITHUB_ENV
          echo "TARGET_REPO=qhr-local-maven-gradle-plugins-secure-release" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Config JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ENV_1: ${{ secrets.ARTIFACTORY_CLI_CONFIG }}

      - name: Gather Artifactory Build Info
        run: |
          export JFROG_CLI_BUILD_NAME="Gradle Convention Plugins"
          export JFROG_CLI_BUILD_NUMBER="${{ github.ref_name }}"
          echo "JFROG_CLI_BUILD_NAME=${JFROG_CLI_BUILD_NAME}" >> $GITHUB_ENV
          echo "JFROG_CLI_BUILD_NUMBER=${JFROG_CLI_BUILD_NUMBER}" >> $GITHUB_ENV
          jfrog rt build-collect-env
          jfrog rt build-add-git

      - name: Publish Packages to Artifactory
        run: |
          jfrog gradle-config --use-wrapper=true --uses-plugin=true --deploy-maven-desc=true --deploy-ivy-desc=false \
             --repo-deploy ${TARGET_REPO:=qhr-local-maven-gradle-plugins-secure-snapshot}
          jfrog gradle artifactoryPublish

      - name: Publish Artifactory Build
        run: |
          jfrog rt build-publish
